import type { ItTicket } from "@/types/it";

/**
 * Chamados da Central de Motoristas.
 * Reaproveitam a forma de `ItTicket` para alimentar o mesmo kanban.
 */
export const DRIVER_TICKETS: readonly ItTicket[] = [
  {
    id: "3021",
    code: "#3021",
    title: "Entrega — Av. Dom Luís, 1200",
    category: "Aplicativos",
    requesterName: "Ana Ribeiro",
    requesterUnit: "Unidade 1",
    requesterSector: "Logística",
    status: "PENDENTE",
    openedAt: "2026-07-22",
    openedLabel: "22/07/2026",
    timeLabel: "08:10",
  },
  {
    id: "3019",
    code: "#3019",
    title: "Coleta de insumos — Fornecedor Norte",
    category: "Equipamentos",
    requesterName: "Diego Alves",
    requesterUnit: "Unidade 2",
    requesterSector: "Produção",
    status: "PENDENTE",
    openedAt: "2026-07-22",
    openedLabel: "22/07/2026",
    timeLabel: "09:40",
  },
  {
    id: "3015",
    code: "#3015",
    title: "Manutenção preventiva — placa ABC-1234",
    category: "Equipamentos",
    requesterName: "João Motta",
    requesterUnit: "Unidade 1",
    requesterSector: "Logística",
    status: "ATRIBUIDO",
    openedAt: "2026-07-21",
    openedLabel: "21/07/2026",
    timeLabel: "14:25",
    assignee: "Pedro Dias",
  },
  {
    id: "3012",
    code: "#3012",
    title: "Transferência entre lojas — Iguatemi",
    category: "Internet e Rede",
    requesterName: "Fernanda Lima",
    requesterUnit: "OKEY Store (Iguatemi)",
    requesterSector: "Comercial",
    status: "EM_ANDAMENTO",
    openedAt: "2026-07-21",
    openedLabel: "21/07/2026",
    timeLabel: "10:05",
    assignee: "João Motta",
  },
  {
    id: "3004",
    code: "#3004",
    title: "Entrega de amostras — Centro Fashion",
    category: "Acessos e Segurança",
    requesterName: "Carlos Mendes",
    requesterUnit: "Lov Club (Centro Fashion)",
    requesterSector: "Comercial",
    status: "CONCLUIDO",
    openedAt: "2026-07-18",
    openedLabel: "18/07/2026",
    timeLabel: "07:50",
    assignee: "Gustavo Rocha",
    durationLabel: "2h 40m",
  },
];
